# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c68a3b6c288a1a875bbe24067c29e520d4bce3b992cb86fa469a46267c27e878efa72630dbf61945e24aaf94a698985885af9a1f950dd60d69f229a547b31558

test:
  secret_key_base: b56ca616bc7aa3f4391e297d30a65d476415cd8f114e529ab403ab149ed89aca245fcdb1454b2f30c3049ae36654e48c9bde55d71e1bfda65545dc96ccc44643

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
